name: Daily Updates

on:
  # 1) Scheduled run (03:00 UTC every day)
  schedule:
    - cron: '0 3 * * *'
  # 2) Manual trigger from the Actions UI
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # your CASE_SEARCH_URL in Settings → Secrets
      URL: ${{ secrets.CASE_SEARCH_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # It's often better to install system dependencies before setting up Python
      - name: Install system dependencies for Chromium
        run: |
          echo "Installing system dependencies for Chromium..."
          sudo apt-get update
          # Install chromium-browser and common dependencies needed for headless operation
          # Adjust the list if your specific library (like Playwright/Selenium) has different requirements
          sudo apt-get install -y chromium-browser 
          echo "System dependencies installed."

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          echo "Installing Python dependencies..."
          python -m pip install --upgrade pip
          # Check if requirements.txt exists before trying to install from it
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
            echo "Python dependencies installed from requirements.txt."
          else
            echo "requirements.txt not found, skipping pip install."
          fi

      # Add a step to run your actual Python script
      # Replace 'main.py' with the actual name of your script if different
      - name: Run script
        run: |
          echo "Running Python script..."
          python test.py $URL
          echo "Script finished."